### ISSUE TITLE
Is it possible to generate models from XSD?

### ISSUE THREAD

**Issue by Pupix** [bpmn-io/moddle#22]
Hello! This is more of a question.
Is it possible to generate the models from already existing XSD schemas?

I am trying to proxy/abstract an XML API with a JSON API in front of it. So far I haven't been able to find any module(s) that help do that, yours (with [moddle-xml](https://github.com/bpmn-io/moddle-xml)) is the closest to what I am looking for.

This is a simple explainer of what I am trying to achieve:
1. Requester sends a JSON to my API
2. Convert said JSON into XML
3. Proxy the created XML to the provider's XML API
4. Receive the XML response from provider
5. Parse the XML to JSON
6. Respond to the original requester in 1 using the parsed JSON

Cheers,
Pupix

**Comment by nikku** [comment]
The reason we did not build our model on top of XML schema definitions is the fact that XSDs hide important information, such as (1) type information in relationships. Example: Often times references are only defined as `QName` while in fact referenced elements must be of specific types according to the actual meta-model.

At the same time I've learned that XSDs can be arbitrarily complex and parsing + interpreting them can be a night mare. 

So as far as I know the answer to your question is no. No, there is no way to auto-generate the models from XSD. There is a way to generate the models from other meta-model descriptors such as [CMOF](https://en.wikipedia.org/wiki/Meta-Object_Facility). We're doing that to generate a [meta-model for BPMN](https://github.com/bpmn-io/bpmn-moddle/blob/master/test/spec/adapter/cmof/generate-simple.js#L13) based on CMOF files.

Depending on your requirements you may still come up with a solution. If it involves this library and possibly [moddle-xml](https://github.com/bpmn-io/moddle) drop us a line. We like to know about it. 

Hope this clarified things a bit.

**Comment by Pupix** [comment]
Thanks for the fast response. I will look into it and see if I can find a way to make it work. I also found [jsonix](https://github.com/highsource/jsonix) that seems to be able to generate JSON schemas from xsd. I may just use this to precompile the mappings and then pass them to moddle-xml. Will late you know, cheers.

**Comment by leog** [comment]
Hey @Pupix. Did you finally went with that approach `jsonix` -> JSON schemas -> `moddle-xml`? I was actually trying to do something similar and was looking the very same thing from moddle.

**Comment by Pupix** [comment]
Hey @leog, sorry for the late response.
I ended up using a combination of `xmlbuilder` and `xml2js` to send an read data.
