### ISSUE TITLE
Effictient way to clone ModdleElement  ?

### ISSUE THREAD

**Issue by g00fy-** [bpmn-io/moddle#23]
Is there a way to efficently clone `ModdleElement` other than `toXML` & `fromXML` ?

**Comment by pinussilvestrus** [comment]
Can you explain a little more in detail what you want to achieve? This would help us to help you.

**Comment by pinussilvestrus** [comment]
Let's close this since new bug report or feature request seem to be included here. Please refer to [our forum](https://forum.bpmn.io/) for such questions, the GitHub issues are not intended for this. 

Feel free to re-open this one if you experience further problems.
