### ISSUE TITLE
Suggestion to remove Element from BUILTIN types

### ISSUE THREAD

**Issue by fra-pa** [bpmn-io/moddle#30]
Hi,

thanks for the moddle library, I try to use it in a project. Unfortunately, some
of the tests fail because moddle defines a built-in type ‘Element’ and the model
I want to implement (UML) uses an equaly named type as the root of its
inheritance hierarchy. This results in an incomplete descriptor, where
‘uml:Element’ is missing.

Besides from my use case, I don’t understand why Element is a built-in type. In
contrast to the other four types (String, Boolean, Integer and Real) Element
does not have any semantics or meaning and is not what I would call a basic data
type. It should better be defined in the context of a specific domain (imho).

I can see a value in the definiton of some fundamental data types. But the
implementation lacks a namespace to allow proper seperation.

Even though the removal might raise issues with existing implementations, the
resulting compatibility problems can be fixed by simply adding Element to the
model. On the other hand, I cannot find an easy workaround if a type with this
name is part of the model to be implemented, like in my use case.

Maybe I miss something and there is already a way to avoid such type conflicts?

Regards,
Frank

**Comment by barmac** [comment]
Hi,

I've just created a test case which verifies that `uml:Element` can be created. Have a look at this here: https://github.com/bpmn-io/moddle/pull/32

Can you please share your descriptor so that I can see the conflict?

**Comment by fra-pa** [comment]
In UML, `Element` is abstract and therefore only subclasses are instantiated. I added a [test](https://github.com/bpmn-io/moddle/pull/31/commits/1ede924ce65ea5c569d46d53020c9af2f9bc9634) in my [PR](https://github.com/bpmn-io/moddle/pull/31) to show where the problem occurs. If you run this test with `Element` included in `BUILTINS` it fails in [line 43](https://github.com/fra-pa/moddle/blob/1ede924ce65ea5c569d46d53020c9af2f9bc9634/test/spec/element.js#L43):
```javascript
expect(instance.$instanceOf('e:Element')).to.be.true;
```

This looks like the same test that you perform. But in this case it's for the inherited type. Here is the descriptor for `e:NamedElement`:
```javascript
{
  ns: { name: 'e:NamedElement', prefix: 'e', localName: 'NamedElement' },
  name: 'e:NamedElement',
  allTypes: [
    { name: 'Element' },
    {
      name: 'e:NamedElement',
      superClass: [Array],
      properties: [Array],
      extends: [],
      meta: {},
      ns: [Object],
      propertiesByName: [Object]
    }
  ],
  allTypesByName: {
    Element: { name: 'Element' },
    'e:NamedElement': {
      name: 'e:NamedElement',
      superClass: [Array],
      properties: [Array],
      extends: [],
      meta: {},
      ns: [Object],
      propertiesByName: [Object]
    }
  },
  properties: [ { name: 'name', type: 'String', ns: [Object], inherited: true } ],
  propertiesByName: {
    name: { name: 'name', type: 'String', ns: [Object], inherited: true },
    'e:name': { name: 'name', type: 'String', ns: [Object], inherited: true }
  }
}
```
It contains `Element` and not `e:element` and is the reason why `$instanceOf()` fails.

Hope this makes the problem more explicit and helps to understand the reason for this issue.

**Comment by nikku** [comment]
There exists a simple workaround I believe. Simply rename the UML element to `BaseElement` and it works. Won't be the cleanest as it does not 1:1 map with the meta-model anymore but should work, right?

**Comment by fra-pa** [comment]
You're right, renaming works and can be done with some scripting. I already evaluated this. But, as you mention, it's a workaround and not a clean solution. If possible, I'd like to avoid this.

Removing `Element` on the other hand, looks like a real solution and may also prevent others from running into the same problem. It's trivial to implement and I cannot see any negative side-effects. If a model needs a reference to this type, it's either already defined (inside the model itself or somewhere else) or can easily be added.

I can see some value in providing built-in types. But as long as they are in the global namespace, they can not be seperated from model types and there's a potential for conflicting names. Providing a namespace for the built-in types could be another clean solution (something like [Primitive Types](https://www.omg.org/spec/UML/20161101/PrimitiveTypes.xmi)).

I guess there was a reason to make `Element` a built-in type, but for me it just looks like an arbitrary name. All the other defined `BUILTINS` are widely-used fundamental data types and have a (more or less) well defined meaning. But `Element` does not fall into this category. Maybe you can tell me, why it was added or a use-case where it's needed?

From my perspective, the predefined type `Element` is a limitation and the removal makes *moddle* a little more general as it allows any model to define a type with this name by itself.

**Comment by nikku** [comment]
@fra-pa The negative side effect is that it essentially breaks _all_ models out there that rely on extending:

* bpmn-moddle
* dmn-moddle
* cmmn-moddle

All of these packages rely on `Element` to be _a generic extension point that takes any element_. We could have decided to call element `Any` in 2014. Unfortunately we called it `Element`.

What we could settle on is allowing explicit namespacing, i.e. you could reference your UML element as `uml:Element` to distinguish it from the built-in type. If that would solve your issue we could verify this works. We cannot easily rename or remove the built in `Element` type.

Maybe I'm also missing something here...

**Comment by nikku** [comment]
Note that namespacing these built-in names does already work.

* You define the `Element` type
* You use it in namespaced form, i.e. `uml:Element`

Cf. https://github.com/bpmn-io/moddle/pull/35

**Comment by nikku** [comment]
Closing this, as the proper solution exists :arrow_up:

**Comment by fra-pa** [comment]
@nikku 
Thank you for the explanation. These are good reasons to keep `Element` in `BUILTINS`.

> Note that namespacing these built-in names does already work.
> 
>     * You define the `Element` type
> 
>     * You use it in namespaced form, i.e. `uml:Element`

Great, this works and solves the problem in an easy way!

I just didn't expect that prefixing the references to `Element` inside the context of the model where the type is defined creates a different descriptor. I'd rather expected it to work the other way around, that it would be necessary to reference the outer context (e.g. `::Element` as a reference to `BUILTINS.Element`) and default is the nearest definition.

Thanks!

**Comment by nikku** [comment]
The `::Element` thing also sounds like a reasonable addition and it won't break any existing uses of that extension point:

* If model defines `Element`, `Element` references model defined element, built-in `Element` must be accessed via `::Element`
* If model does not define `Element` then the built-in `Element` can be accessed via `Element`, too

We'll not be able to follow up on this one. But if you'd like to contribute a PR, we are open for it.
