### ISSUE TITLE
Provide JSON schema for moddle (including XML extension elements)

### ISSUE THREAD

**Issue by zambrovski** [bpmn-io/moddle#62]
### Is your feature request related to a problem? Please describe.

As a developer, I want to make sure that my moddle schema instance is checked against a moddle schema definition and any violations are reported by a standard schema validation tool.

### Describe the solution you'd like

Provide a complete JSON schema. The parts references in docs folder are helpful, but incomplete.

### Describe alternatives you've considered

None

### Additional context

I developed a JSON schema and would like you to double check it and include into this repository.

**Comment by nikku** [comment]
> I developed a JSON schema and would like you to double check it and include into this repository.

Sounds like you want to contribute it (as a PR)? We'd highly apprechiate that. We discussed this topic in the past, but were not able to follow through yet.
